# example
PI <- vect("GIS/world_borders_PI.shp")
tmp <- rast(c("GIS/wc2.0_bio_5m_01.tif", "GIS/wc2.0_bio_5m_06.tif"))
prc <- rast(c("GIS/wc2.0_bio_5m_12.tif", "GIS/wc2.0_bio_5m_14.tif"))
vars <- c(tmp, prc)
chilus <- read.table("GIS/chilus.csv", sep=";", header=TRUE)
vals <- extract(vars, chilus, ID=FALSE)

bc <- bioclim(vals, vars)
ch <- convexHullModel(vals, vars)
km <- kernelModel(vals, vars)
dm <- domainmodel(vals, vars)
md <- mahalanobisModel(vals, vars)
mvn <- mvnormalModel(vals, vars)

bc <- model(vals, vars, method = "bioclim")
ch <- model(vals, vars, method = "convexhull")
km <- model(vals, vars, method = "kernel")
dm <- model(vals, vars, method = "domain")
md <- model(vals, vars, method = "mahalanobis")
mvn <- model(vals, vars, method = "mvnormal")

layout(matrix(1:6, 3))
plot(bc[[1]], main="bioclim")
plot(ch[[1]], main="Convex Hull")
plot(km[[1]], main="Kernel")
plot(dm[[1]], main="Domain")
plot(mm[[1]], main="Mahalanobis ")
plot(mvn[[1]], main="Multivariate Normal")
